spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

